### ISSUE TITLE
RecyclerView好像有点问题

### ISSUE THREAD

**Issue by Xiaocai9527** [georgeyang1024/DoubleScroll#1]
title指向RecyclerView的时候，一开始事件就交给scrollableView进行分发了。
还有就是水平滑动有时候有点冲突，你看这样是不是好一点：
`if (Math.abs(detalY) > Math.abs(detalX)) {
    //加一个判断水平还是上下滑动，只有上下滑动的时候才会有上滑和下拉
                        if (isUp) {
                            Log.d("xiao", "maxMoveY:" + maxMoveY);
                            if (getScrollY() >= maxMoveY) {
                                Log.d("xiao", "hah:");
                                event.transform(eventMatrix);//将变换矩阵应用于事件中的所有点
                                return scrollableView.dispatchTouchEvent(event);
                            }
                        } else if (isDown) {
                            if (!ViewUtil.isScrollToTop(scrollableView)) {//如果可滑动的view没有滑到顶部
                                event.transform(eventMatrix);//将变换矩阵应用于事件中的所有点
                                return scrollableView.dispatchTouchEvent(event);
                            }
                        }
                    }`

**Comment by georgeyang1024** [comment]
这个bug是由于RecyclerView嵌套在scrollview时，recycleview默认开启NestedScrolling跟scrollview冲突了，关闭即可。

recyclerView.setNestedScrollingEnabled(false)

http://stackoverflow.com/questions/38074949/recyclerview-inside-scrollview-some-items-are-not-shown
